config/routes.rb
Rails.application.routes.draw do
  resources :academies
  resources :trainers
  resources :clients
  resources :dogs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root'pages#dashboard'
  get 'about', to: 'pages#about'
  get 'dashboard', to: 'pages#dashboard'
  get '/search', to: 'trainers#search'
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]

  # GET /dogs or /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1 or /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs or /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: "Dog was successfully created." }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1 or /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: "Dog was successfully updated." }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1 or /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: "Dog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:name, :breed, :description, :age, :gender, :coat_length, :size)
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
  <div class ="container"> 
    <%= form_with(model: dog) do |form| %>
      <% if dog.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

          <ul>
            <% dog.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control'%>
      </div>

      <div class="field">
        <%= form.label :breed %>
        <%= form.text_field :breed, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :age %>
        <%= form.text_field :age , class: 'form-control'%>
      </div>

      <div class="field">
        <%= form.label :gender %>
        <%= form.text_field :gender, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :coat_length %>
        <%= form.text_field :coat_length, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :size %>
        <%= form.text_field :size, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %> 
  </div> 

app/views/dogs/edit.html.erb
<h1><center>Editing Dog</center></h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>


<div class="card mb-4">
  <div class="card-header">
      <i class="fas fa-table me-1"></i>
      <h1><center>Dogs</center></h1>
  </div>
  <div class="card-body">
    <table id="datatablesSimple" class= "dataTable-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Breed</th>
          <th>Age</th>
          <th>Gender</th>
          <th>Coat Length</th>
          <th>Size</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @dogs.each do |dog| %>
          <tr>
            <td><%= dog.name %></td>
            <td><%= dog.breed %></td>
            <td><%= dog.age %></td>
            <td><%= dog.gender %></td>
            <td><%= dog.coat_length %></td>
            <td><%= dog.size %></td>
            <td><%= dog.description %></td>
            <td><%= link_to 'Show', dog %></td>
            <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
            <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Dog', new_dog_path, class: "btn btn-outline-dark" %>

app/views/dogs/new.html.erb
<h1><center>New Dog</center></h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dog.description %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>