config/routes.rb
Rails.application.routes.draw do
  resources :academies
  resources :trainers
  resources :clients
  resources :dogs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root'pages#dashboard'
  get 'about', to: 'pages#about'
  get 'dashboard', to: 'pages#dashboard'
  get '/search', to: 'trainers#search'
end

app/views/pages/about.html.erb
<h1>About page.</h1>

app/views/pages/dashboard.html.erb
<main>
     <div class="container-fluid px-4">
        <h1 class="mt-4">Dogpress</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="/clients">Clients</a></li>
                <li class="breadcrumb-item"><a href="/trainers">Trainers</a></li>
                <li class="breadcrumb-item"><a href="/dogs">Dogs</a></li>
                <li class="breadcrumb-item"><a href="/academies">Academies</a></li>
             </ol>
        <%= link_to 'academies', academies_path %>
        <%= link_to 'clients', clients_path %>
        <%= link_to 'trainers', trainers_path %>
        <%= link_to 'dogs', dogs_path %> 
    </div>
             <!--
                        <div class="card mb-4">
                            <div class="card-body">
                                DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the
                                <a target="_blank" href="https://datatables.net/">official DataTables documentation</a>
                                .
                            </div>
                        </div>
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                DataTable Example
                            </div>
                            <div class="card-body">
                                <table id="datatablesSimple">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Phone</th>
                                            <th>Address</th>
                                            <th># of dogs</th>
                                            <th>Program enrollment(s)</th>
                                            <th>Document(s)</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Phone</th>
                                            <th>Address</th>
                                            <th># of dogs</th>
                                            <th>Program enrollment(s)</th>
                                            <th>Document(s)</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        <tr>
                                            <td>Harry Potter</td>
                                            <td>Harry@Hoggy.com</td>
                                            <td>666-666-6666</td>
                                            <td>324 Wizard Road, Sin City 80412</td>
                                            <td>2</td>
                                            <td>puppy</td>
                                            <td>pdf files here.</td>
                                        </tr>
                                        <tr>
                                            <td>Harry Potter</td>
                                            <td>Harry@Hoggy.com</td>
                                            <td>666-666-6666</td>
                                            <td>324 Wizard Road, Sin City 80412</td>
                                            <td>2</td>
                                            <td>puppy</td>
                                            <td>pdf files here.</td>
                                        </tr>
                                        <tr>
                                            <td>Harry Potter</td>
                                            <td>Harry@Hoggy.com</td>
                                            <td>666-666-6666</td>
                                            <td>324 Wizard Road, Sin City 80412</td>
                                            <td>2</td>
                                            <td>puppy</td>
                                            <td>pdf files here.</td>
                                        </tr>
                                        <tr>
                                            <td>Harry Potter</td>
                                            <td>Harry@Hoggy.com</td>
                                            <td>666-666-6666</td>
                                            <td>324 Wizard Road, Sin City 80412</td>
                                            <td>2</td>
                                            <td>puppy</td>
                                            <td>pdf files here.</td>
                                        </tr>
                                        <tr>
                                            <td>Harry Potter</td>
                                            <td>Harry@Hoggy.com</td>
                                            <td>666-666-6666</td>
                                            <td>324 Wizard Road, Sin City 80412</td>
                                            <td>2</td>
                                            <td>puppy</td>
                                            <td>pdf files here.</td>
                                        </tr>
                                        <tr>
                                            <td>Harry Potter</td>
                                            <td>Harry@Hoggy.com</td>
                                            <td>666-666-6666</td>
                                            <td>324 Wizard Road, Sin City 80412</td>
                                            <td>2</td>
                                            <td>puppy</td>
                                            <td>pdf files here.</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; DogPress 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="dogpress_template/dist/js/scripts.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="dogpress_template/dist/js/datatables-simple-demo.js"></script>
    </body>
</html>


<br>
-->

app/views/pages/index.html.erb
    <h1>Dogpress.</h1>
    <p>Dog management made simple.</p>