config/routes.rb
Rails.application.routes.draw do
  resources :academies
  resources :trainers
  resources :clients
  resources :dogs
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root'pages#dashboard'
  get 'about', to: 'pages#about'
  get 'dashboard', to: 'pages#dashboard'
  get '/search', to: 'trainers#search'
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: %i[ show edit update destroy ]

  # GET /trainers or /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1 or /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers or /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: "Trainer was successfully created." }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1 or /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: "Trainer was successfully updated." }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1 or /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: "Trainer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].blank? 
      redirect_to trainers_path and return
    else
      @parameter = params[:search].downcase
      @results = Trainer.all.where("lower(trainers.first_name) LIKE :search", search: "%#{@parameter}%")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trainer_params
      params.require(:trainer).permit(:full_name, :first_name, :last_name)
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.erb
  <div class ="container"> 
    <%= form_with(model: trainer) do |form| %>
      <% if trainer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

          <ul>
            <% trainer.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :full_name %>
        <%= form.text_field :full_name, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div> 

app/views/trainers/edit.html.erb
<h1><center>Editing Trainer</center></h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>
<main>
<div class="card mb-4">
  <div class="card-header">
      <i class="fas fa-table me-1"></i>
      <h1><center>Trainers</center></h1>
  </div>
  <div class = "container">
    <%= form_tag(search_path, :method => "get") do %>
      <div class = "input-group">
        <%= search_field_tag :search, params[:search], placeholder: "Search for trainer", class: "form-control" %>
        <div class= "input-group-btn">
          <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
        </div>
      </div>
    <% end %>
  </div> 
  <div class="card-body">
    <table id="datatablesSimple" class= "dataTable-table">
      <thead>
        <tr>
          <th>Full name</th>
          <th>First name</th>
          <th>Last name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @trainers.each do |trainer| %>
          <tr>
            <td><%= trainer.full_name %></td>
            <td><%= trainer.first_name %></td>
            <td><%= trainer.last_name %></td>
            <td><%= link_to 'Show', trainer %></td>
            <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
            <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</main>
<br>

<%= link_to 'New Trainer', new_trainer_path, class: "btn btn-outline-dark" %>

app/views/trainers/new.html.erb
<h1><center>New Trainer</center></h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/search.html.erb
<h3>Search Results</h3>

<% @results.each do |result| %> 
    <%= result.first_name %>
    <%= result.last_name %>
    <br/>
<% end %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @trainer.full_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @trainer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @trainer.last_name %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>